<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
    <RootNamespace>FleetManagement.Actors</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="ActorMessages.fs" />
    <Compile Include="VehicleActor.fs" />
    <Compile Include="RouteCalculatorActor.fs" />
    <Compile Include="TelemetryStreamActor.fs" />
    <Compile Include="FleetSupervisorActor.fs" />
    <Compile Include="Tracing.fs" />
    <Compile Include="ClusterBootstrap.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FleetManagement.Core\FleetManagement.Core.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Akka"                            Version="1.5.*" />
    <PackageReference Include="Akka.Coordination" Version="1.5.67" />
    <PackageReference Include="Akka.Discovery" Version="1.5.67" />
    <PackageReference Include="Akka.FSharp"                    Version="1.5.*" />
    <PackageReference Include="Akka.Persistence" Version="1.5.67" />
    <PackageReference Include="Akka.Remote"                    Version="1.5.*" />
    <PackageReference Include="Akka.Cluster"                   Version="1.5.*" />
    <PackageReference Include="Akka.Cluster.Tools"             Version="1.5.*" />
    <PackageReference Include="Akka.Cluster.Sharding"          Version="1.5.*" />
    <PackageReference Include="Akka.Streams"                   Version="1.5.*" />
    <PackageReference Include="Akka.Serialization.Hyperion"    Version="1.5.*" />
    <PackageReference Include="OpenTelemetry" Version="1.15.3" />
    <PackageReference Update="FSharp.Core" Version="10.1.203" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
  </ItemGroup>
</Project>
